apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: otus-homework-06
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: osmenogg/otus-homework-06
    custom:
      buildCommand: ./build.sh

deploy:
  helm:
    releases:
      - name: otus-hw-06
        chartPath: ./k8s/user_service
        namespace: otus
        recreatePods: true
        artifactOverrides:
          image: osmenogg/otus-homework-06
        imageStrategy:
          helm: {}
